name: fireauth_ui
description: Allows you to quickly connect common Firebase auth with basic UI
version: 0.0.2
author: manhinhang <manhinhang@gmail.com>
homepage: https://github.com/manhinhang/flutter_fireauth_ui

environment:
    sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.5.11"
  google_sign_in: "^3.0.4"
  flutter_facebook_login: "^1.1.1"
  flutter_localizations:
      sdk: flutter

dev_dependencies:
  intl_translation: "^0.16.6"
  flutter_test:
      sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    androidPackage: com.manhinhang.fireauthui
    pluginClass: FireauthUiPlugin

  assets:
    - images/btn_facebook_icon.png
    - images/btn_google_icon.png
